### ISSUE TITLE
something about enhance_speach.py

### ISSUE THREAD

**Issue by Mitchell1314** [iTaa/soja_box#1]
Hi sir,
    When I run your "enhance_speach.py", some errors occur:
![image](https://user-images.githubusercontent.com/15179223/35470025-33206722-037c-11e8-91f2-ced0fe757189.png)
can you tell me what happend and how to fix it? Waiting for your reply. Thank you.

**Comment by itaa** [comment]
I test it use win10 with python3.6.1 is not appear this problem, you can check you python version and use I provide audio file try again.
