### ISSUE TITLE
您好，请问我用自己录的音频测试，去噪后，整个音频只有前半部分有声音，后面都没声音是什么原因

### ISSUE THREAD

**Issue by JK-Hugol** [iTaa/soja_box#2]
您好，请问我用自己录的音频测试，去噪后，整个音频只有前半部分有声音，后面都没声音是什么原因，请问作者的音频是什么格式，谢谢了

**Comment by itaa** [comment]
我这里使用的是标准的`wav`格式，使用`wave.open("input_file.wav")`打开的，如果你的不是`wav`格式，可以使用`ffmpy`转换，`ffmpy`文档参考：https://ffmpy.readthedocs.io/en/latest/

**Comment by JK-Hugol** [comment]
你好，我的音频文件是通过程序用麦克风录的，也是wav格式，采样频率16000，比特率256kbps,，去噪后整个音频都没有声音，请问作者你的音频采样频率是多少，或者作者是用什么方式录制音频，谢谢了

**Comment by itaa** [comment]
我是写程序录制的
